# Generated by Django 2.1.5 on 2019-04-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20190403_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectstatus',
            old_name='How',
            new_name='how',
        ),
        migrations.RenameField(
            model_name='projectstatus',
            old_name='What',
            new_name='what',
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='when',
            field=models.DateTimeField(verbose_name='date committed'),
        ),
    ]
