# Generated by Django 2.1.5 on 2019-04-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_auto_20190403_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='when',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
