# Generated by Django 2.1.5 on 2019-04-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_auto_20190403_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
