# Generated by Django 2.1.5 on 2019-04-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_auto_20190404_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='who',
            field=models.CharField(default='', max_length=20),
        ),
    ]
